config/routes.rb
SplineLatest::Application.routes.draw do
  resources :chats

  resources :comments

  resources :presentations

  resources :whiteboards

  resources :videos

 ActionController::Routing::Routes.draw do |map|
   map.connect 'presentations/:id/delete', :controller=>'presentations', :action=>'destroy'
   map.connect ':controller/:action/:id'
   map.connect ':controller/:action/:id.:format'
   map.connect ':controller/:action'
 end

   root :to => "spline#index"

end

app/models/video.rb
class Video < ActiveRecord::Base

has_many :comments
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.xml
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.xml
  # def show
  #  @video = Video.find(:all)

  # respond_to do |format|
  #    format.html { redirect_to  "/" }
  #    format.xml  { render :xml => @video }
  #  end
 # end

  # GET /videos/new
  # GET /videos/new.xml
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.xml
  def create
    @video = Video.new(params[:video])
    @video.video_url="/RandyPausch.flv"
    @video.timeline=@video.video_time
    respond_to do |format|
      if @video.save
        format.html { redirect_to  "/" }
        format.xml  { render :xml => @video, :status => :created, :location => @video }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.xml
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to(@video, :notice => 'Video was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.xml
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to(videos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<div style="display:none">
<form action="/videos" class="new_bookmark" id="new_bookmark" method="post" name="autoSubmit">
<input type="text" id="time1" name="video[video_time]" />
<input type="text" id="topic" name="video[topic]" />
</form>
</div>		

app/views/videos/_index.html.erb
<a
			 href="/Randy_Pausch.flv"
			 style="display:block;width:520px;height:360px"
			 id="player" >
</a>
<script>

			var j=0;
var fd;
			var player=flowplayer("player", "/swf/flowplayer-3.2.7.swf",{clip: {
onStart: function () {
      fd = parseInt(this.getClip().fullDuration, 10);
      
   },
			autoPlay:false,
			autoBuffering:true,
			start:5,

			
				}
			});


</script>

<%= render 'videos/new'%>

app/views/videos/_new.html.erb
<%= render 'videos/form' %>

app/views/videos/_show.html.erb
<table id="topics" style="border:1px solid black">
<% videos.each do |video|%>
	<tr>
	<td bgcolor="#ffffff" onclick=change(<%= video.video_time%>)><%= video.topic%></td>
	<td><%= video.video_time%> </td>
	</tr>
<% end %>
</table>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>