config/routes.rb
SplineLatest::Application.routes.draw do
  resources :chats

  resources :comments

  resources :presentations

  resources :whiteboards

  resources :videos

 ActionController::Routing::Routes.draw do |map|
   map.connect 'presentations/:id/delete', :controller=>'presentations', :action=>'destroy'
   map.connect ':controller/:action/:id'
   map.connect ':controller/:action/:id.:format'
   map.connect ':controller/:action'
 end

   root :to => "spline#index"

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  # GET /chats
  # GET /chats.xml
  def index
    
  end
  def send_data
    render :juggernaut do |page|
      page.alert('hi')
    end
    render_juggernaut(:action => 'whatever')
  end
  def create
    
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chats/chat.html.erb
<% juggernaut   %>

app/views/chats/create.html.erb
<% juggernaut %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<%= juggernaut %>
 <%= form_tag(
	          :url => { :action => :send_data },
	          :complete => "$('chat_input').value = ''" ) %>
	      <%= text_field_tag( 'chat_input', '', { :size => 20, :id => 'chat_input'} ) %>
	      <%= submit_tag "Add" %>
	    </form>
	    <ul id="chat_data" style="list-style:none">
	    </ul>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>