config/routes.rb
SplineLatest::Application.routes.draw do
  resources :chats

  resources :comments

  resources :presentations

  resources :whiteboards

  resources :videos

 ActionController::Routing::Routes.draw do |map|
   map.connect 'presentations/:id/delete', :controller=>'presentations', :action=>'destroy'
   map.connect ':controller/:action/:id'
   map.connect ':controller/:action/:id.:format'
   map.connect ':controller/:action'
 end

   root :to => "spline#index"

end

app/models/whiteboard.rb
class Whiteboard < ActiveRecord::Base
end

app/controllers/whiteboards_controller.rb
class WhiteboardsController < ApplicationController
  # GET /whiteboards
  # GET /whiteboards.xml
  def index
    @whiteboards = Whiteboard.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @whiteboards }
    end
  end

  # GET /whiteboards/1
  # GET /whiteboards/1.xml
  def show
    @whiteboard = Whiteboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @whiteboard }
    end
  end

  # GET /whiteboards/new
  # GET /whiteboards/new.xml
  def new
    @whiteboard = Whiteboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @whiteboard }
    end
  end

  # GET /whiteboards/1/edit
  def edit
    @whiteboard = Whiteboard.find(params[:id])
  end

  # POST /whiteboards
  # POST /whiteboards.xml
  def create
    @whiteboard = Whiteboard.new(params[:whiteboard])

    respond_to do |format|
      if @whiteboard.save
        format.html { redirect_to(@whiteboard, :notice => 'Whiteboard was successfully created.') }
        format.xml  { render :xml => @whiteboard, :status => :created, :location => @whiteboard }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @whiteboard.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /whiteboards/1
  # PUT /whiteboards/1.xml
  def update
    @whiteboard = Whiteboard.find(params[:id])

    respond_to do |format|
      if @whiteboard.update_attributes(params[:whiteboard])
        format.html { redirect_to(@whiteboard, :notice => 'Whiteboard was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @whiteboard.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /whiteboards/1
  # DELETE /whiteboards/1.xml
  def destroy
    @whiteboard = Whiteboard.find(params[:id])
    @whiteboard.destroy

    respond_to do |format|
      format.html { redirect_to(whiteboards_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/whiteboards_helper.rb
module WhiteboardsHelper
end

app/views/whiteboards/edit.html.erb
<h1>Editing whiteboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @whiteboard %> |
<%= link_to 'Back', whiteboards_path %>

app/views/whiteboards/index.html.erb
<div id="myCanvas">
		<canvas id="canvas" class="clear" height="200" width="300"></canvas>
		<br/>
		

		<table id="panel">
		
		<tr><td><button id="erase">Erase</button></td><td><button id="resetButton">Reset</button></td></tr>

		</table>

		
</div>
	
	

app/views/whiteboards/new.html.erb
<h1>New whiteboard</h1>

<%= render 'form' %>

<%= link_to 'Back', whiteboards_path %>

app/views/whiteboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Timeline:</b>
  <%= @whiteboard.timeline %>
</p>

<p>
  <b>Wb url:</b>
  <%= @whiteboard.wb_url %>
</p>

<p>
  <b>Wb time:</b>
  <%= @whiteboard.wb_time %>
</p>

<p>
  <b>Topic:</b>
  <%= @whiteboard.topic %>
</p>


<%= link_to 'Edit', edit_whiteboard_path(@whiteboard) %> |
<%= link_to 'Back', whiteboards_path %>